[
    {
        "content": "<p>For anyone interested in learning more about python environments, this is a really good write up <a href=\"https://whiteboxml.com/blog/the-definitive-guide-to-python-virtual-environments-with-conda\" target=\"_blank\" title=\"https://whiteboxml.com/blog/the-definitive-guide-to-python-virtual-environments-with-conda\">https://whiteboxml.com/blog/the-definitive-guide-to-python-virtual-environments-with-conda</a></p>",
        "id": 33423,
        "sender_full_name": "Max Grover",
        "timestamp": 1622814792
    },
    {
        "content": "<p>What python  environments  are people using that include dask clients and mapping tools like cartopy, matplotlib and Basemap? I tried using the NPL 2023b, and it supports the dask clients, but doesnâ€™t have these  mapping packages.</p>",
        "id": 86472,
        "sender_full_name": "Gabriela Negrete Garcia",
        "timestamp": 1690902508
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"300\">@Gabriela Negrete Garcia</span>, I took a quick look at the packages in npl-2023b using <code>conda list</code> and it looks like cartopy and matplotlib are in there but basemap is not. To request packages be added to the npl environment, you can either submit a help ticket (<a href=\"http://help.ucar.edu\">help.ucar.edu</a>) or open an issue in this <a href=\"https://github.com/NCAR/ncar-conda/issues\">github repo</a>.</p>",
        "id": 86476,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1690903867
    },
    {
        "content": "<p>Another option that I use a lot is creating your own environment with the packages you want in there.</p>",
        "id": 86477,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1690903918
    },
    {
        "content": "<p>I also cannot use these environments because they typically lack some of the geospatial libraries I need (OGR, GDAL, etc.). I use conda or mamba to create new environments that will contain these libraries and allow me to add new ones.</p>",
        "id": 86556,
        "sender_full_name": "Kevin Sampson",
        "timestamp": 1690993663
    },
    {
        "content": "<p>Hi!  Ok so I think I'm having an issue with the NLP environment on Cheyenne/Casper.  I'm trying to run some automated scripts to restart model runs - these scripts are un on the command line and I do the following: </p>\n<p>module load conda<br>\nconda activate npl</p>\n<p>But when I run my script - I get the following :</p>\n<div class=\"codehilite\"><pre><span></span><code>import numpy as np\n</code></pre></div>\n\n<p>ModuleNotFoundError: No module named 'numpy'</p>\n<p>in another script I get </p>\n<div class=\"codehilite\"><pre><span></span><code>import xarray as xr\n</code></pre></div>\n\n<p>ModuleNotFoundError: No module named 'xarray'</p>\n<p>Other import calls are working - (e.g. import glob,os,re,sys, fnmatch<br>\nfrom math import floor).</p>\n<p>I'm curious what might be going on - I fully acknowledge I might be doing something wrong.  </p>\n<p>Scripts I'm working with are here: /glade/work/rmccrary/icar/cmip/MP_runs/CMIP5/CanESM2_WSM3_hist_1979-2010/scripts/ setup_next_run.py or aggregate_parallel_files.py</p>\n<p>I have no issues with this on jupyter hub - but for some reason nothing seems to be working on the command line.  Am I loading the npl environment incorrectly?</p>",
        "id": 86864,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691511075
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"308\">@Rachel McCrary</span> I am also curious about this. I would have thought that activating NPL would point to the right python libraries so you should be able to use those modules, but I tested this and got the same import error with numpy/xarray. Tagging <span class=\"user-mention\" data-user-id=\"71\">@Negin Sobhani</span> and <span class=\"user-mention\" data-user-id=\"141\">@Brian Vanderwende</span> for any insight here.</p>",
        "id": 86867,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1691512525
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"47\">@Katie Dagon</span>  ok so its not just me?  I fumble around with Python so I always assume I'm doing something wrong - but this is breaking all my model runs! (I haven't run anything in about 6 months, but this system worked just fine in January)</p>",
        "id": 86869,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691513252
    },
    {
        "content": "<p>Thanks for the ping! <span class=\"user-mention\" data-user-id=\"47\">@Katie Dagon</span> - when you tested this, did you use Rachel's script, or did you try a simplified example? I am unable to reproduce it right now, so I'm guessing we are running into some difference in either how we are testing or our environments.</p>\n<p><span class=\"user-mention\" data-user-id=\"308\">@Rachel McCrary</span> - Do you use this on the command line on a login node or in a PBS job? If you type <code>which python</code> at the command line after activating the NPL, what do you get?</p>",
        "id": 86870,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691513328
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"141\">@Brian Vanderwende</span> - I've tried in both a PBS job and a command line on Cheyenne.  When I type which python I get </p>\n<p>/glade/u/apps/opt/conda/bin/python</p>\n<p>I thought it might be something up with the script I was running, but when I just open an interactive python (just by typing python) and trying to import xarray I get the same error ...</p>",
        "id": 86871,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691513469
    },
    {
        "content": "<p>Yes I did the same, just testing <code>python</code> and then <code>import numpy as np</code> after <code>module load conda</code> and <code>conda activate npl</code>. I also got the same path from <code>which python</code>.</p>",
        "id": 86872,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1691513561
    },
    {
        "content": "<p>Ah, that explains why it doesn't work, though not why it is failing. It looks like it is giving you the Python in the base environment, and not the NPL. Thanks for sharing this - I need to figure out why the activation is not working for you two (whereas it is working for me).</p>",
        "id": 86873,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691513614
    },
    {
        "content": "<p>It does work when I use a jupyter notebook :)</p>",
        "id": 86874,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691513724
    },
    {
        "content": "<p>Re: the activation, I have a separate miniconda install and I'm wondering if it doesn't get fully overriden by the <code>module load conda</code>. But <code>conda env list</code> does indicate that I have npl activated, and <code>which conda</code> points to /glade/u/apps/opt/conda/bin/conda</p>",
        "id": 86875,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1691514153
    },
    {
        "content": "<p>It seems plausible, though my miniconda install does get overridden. I suppose it could be a version difference. <span class=\"user-mention\" data-user-id=\"47\">@Katie Dagon</span> I could try initializing your miniconda if you provide me the path and I can see if I get the same result.</p>",
        "id": 86877,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691514314
    },
    {
        "content": "<p>/glade/work/kdagon/miniconda</p>",
        "id": 86878,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1691514401
    },
    {
        "content": "<p>maybe also something in PATH?</p>",
        "id": 86879,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1691514409
    },
    {
        "content": "<p>I also have a miniconda setup and something in my PATH - however I never used to have this problem, so it is a new issue!  Setting all of this up was a bit ad-hoc and asking people what they did, rather than actually knowing what to do :).  I haven't used my own environments in a long time.</p>",
        "id": 86882,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691514517
    },
    {
        "content": "<p>Hmm... okay so I do get the issue using your miniconda, Katie, though not with mine. I'll keep digging.</p>",
        "id": 86884,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691514596
    },
    {
        "content": "<p>My conda version in there is very old <span aria-label=\"grimacing\" class=\"emoji emoji-1f62c\" role=\"img\" title=\"grimacing\">:grimacing:</span> . But as Rachel said, strange that this worked previously for her and it's a new issue.</p>",
        "id": 86886,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1691514748
    },
    {
        "content": "<p>\"new\" is probably since January for me - I almost exclusively use JupyterHub now ...</p>",
        "id": 86887,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691514883
    },
    {
        "content": "<p>We do 2x a year updates to conda itself in the module. It was updated about 1 month ago, so perhaps this broke compatibility with older conda versions in the way we do it in the module. That seems like a reasonable explanation at this point, but looking to test it out myself with an older conda version.</p>",
        "id": 86891,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691515085
    },
    {
        "content": "<p>Ok - and then let me know how I might fix this :)</p>",
        "id": 86893,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691515231
    },
    {
        "content": "<p>The easy fix would be to unload the conda module and run <code>conda update conda</code>, which should bring your miniconda to the latest (and greatest?) version of conda. I'm going to try to make this work again for older miniconda versions, but not sure yet how easy that will be!</p>",
        "id": 86894,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691515335
    },
    {
        "content": "<p>Ok I have this installed in my home directory - which was a bad decision and I was never sure how to move it to my work directory ... can I just move it or do I need to start over?</p>",
        "id": 86897,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691515543
    },
    {
        "content": "<p>In my experience, trying to relocate (mv) conda environments does not work without a bunch of extra steps. Are your environments in your home too, or just miniconda itself?</p>",
        "id": 86898,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691515742
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"141\">@Brian Vanderwende</span>   - I think my environments are in my home too - and honestly I don't really use them I've just used npl!  I have an office hours with someone from the ESDS to discuss what the heck to do with the mess I've made :)</p>",
        "id": 86923,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691522058
    },
    {
        "content": "<p>Ok doing conda update conda did work!  So thanks for that :).</p>",
        "id": 86927,
        "sender_full_name": "Rachel McCrary",
        "timestamp": 1691523223
    },
    {
        "content": "<p>Excellent. Please let us know if you run into any other issues after the virtual help. Thanks again for reporting the issue.</p>",
        "id": 86928,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691523369
    },
    {
        "content": "<p>Thanks for your help with this Brian!</p>",
        "id": 86958,
        "sender_full_name": "Katie Dagon",
        "timestamp": 1691534216
    },
    {
        "content": "<p>Hey all - I've made some changes to the conda module that should make this work better. Now, if you have a conda initialized into your environment, the module will only add our settings, but will leave your conda as the active one, even if the module is loaded. This should avoid these old-new conflicts that Rachel and Katie were seeing. If you do not have conda initialized in your shell, the module will provide you with our conda.</p>\n<p>Let me know if you run into any issues or otherwise have any feedback. Thanks again for reporting these issues to us!</p>",
        "id": 87045,
        "sender_full_name": "Brian Vanderwende",
        "timestamp": 1691680024
    }
]