[
    {
        "content": "<p>I just filed a help ticket (RC-11546) with the following issue:</p>\n<blockquote>\n<p>I am getting repeated \"Invalid response: 502 Bad Gateway\" errors on <a href=\"http://jupyterhub.hpc.ucar.edu\">jupyterhub.hpc.ucar.edu</a>, e.g. when attempting to save a file.  When I refresh the page, I get \"502 Bad Gateway.\" This happened a few moments ago—then it let me back after a refresh. Now I am locked out again.</p>\n</blockquote>\n<p>cc <span class=\"user-group-mention\" data-user-group-id=\"6\">@hpcd</span></p>",
        "id": 48202,
        "sender_full_name": "Matt Long",
        "timestamp": 1639492772
    },
    {
        "content": "<p><a href=\"https://arc.ucar.edu/articles/174\">https://arc.ucar.edu/articles/174</a></p>",
        "id": 48203,
        "sender_full_name": "Jared Baker",
        "timestamp": 1639493328
    },
    {
        "content": "<p>RTFM! Thanks.</p>",
        "id": 48204,
        "sender_full_name": "Matt Long",
        "timestamp": 1639493810
    },
    {
        "content": "<p>But anyways, I think I've finished it now. Things should have stayed running I believe. Some notebook restarts for some extensions may need to take place, but I was able to get a server on each of our resources.</p>",
        "id": 48205,
        "sender_full_name": "Jared Baker",
        "timestamp": 1639493886
    },
    {
        "content": "<p>Would it be helpful to post here too? We've been trying to use a single truth for communications, but I suppose we could do something here as well.</p>",
        "id": 48239,
        "sender_full_name": "Jared Baker",
        "timestamp": 1639508308
    },
    {
        "content": "<p>The dailyB is fine and I think a reasonable place to consolidate that kind of info—in fact, I read about the downtime, I just forgot this morning!</p>",
        "id": 48240,
        "sender_full_name": "Matt Long",
        "timestamp": 1639510111
    }
]