[
    {
        "content": "<p>After the Cheyenne updates last week, I have been able to login the the JupyterHub this week with no problems. However, when I try to open an existing notebook or an existing figure I am unable to do so. Instead I get a \"File Load Error\" when I try to load the image and a \"Close without saving error?\" message when I try to open a notebook. Any thoughts on why this might be happening or possible solutions?</p>",
        "id": 14250,
        "sender_full_name": "Genevieve Elsworth",
        "timestamp": 1595348528
    },
    {
        "content": "<p><a href=\"/user_uploads/2/43/2gHuoU9q5jplkzzmLoqbxxmB/Screen-Shot-2020-07-21-at-10.18.35-AM.png\" target=\"_blank\" title=\"Screen-Shot-2020-07-21-at-10.18.35-AM.png\">Screen-Shot-2020-07-21-at-10.18.35-AM.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/43/2gHuoU9q5jplkzzmLoqbxxmB/Screen-Shot-2020-07-21-at-10.18.35-AM.png\" target=\"_blank\" title=\"Screen-Shot-2020-07-21-at-10.18.35-AM.png\"><img src=\"/user_uploads/2/43/2gHuoU9q5jplkzzmLoqbxxmB/Screen-Shot-2020-07-21-at-10.18.35-AM.png\"></a></div>",
        "id": 14251,
        "sender_full_name": "Genevieve Elsworth",
        "timestamp": 1595348535
    },
    {
        "content": "<p><a href=\"/user_uploads/2/ae/wlOzVgZik_JLciFqSMM8VaIm/Screen-Shot-2020-07-21-at-10.18.54-AM.png\" target=\"_blank\" title=\"Screen-Shot-2020-07-21-at-10.18.54-AM.png\">Screen-Shot-2020-07-21-at-10.18.54-AM.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/ae/wlOzVgZik_JLciFqSMM8VaIm/Screen-Shot-2020-07-21-at-10.18.54-AM.png\" target=\"_blank\" title=\"Screen-Shot-2020-07-21-at-10.18.54-AM.png\"><img src=\"/user_uploads/2/ae/wlOzVgZik_JLciFqSMM8VaIm/Screen-Shot-2020-07-21-at-10.18.54-AM.png\"></a></div>",
        "id": 14252,
        "sender_full_name": "Genevieve Elsworth",
        "timestamp": 1595348540
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"52\">@Genevieve Elsworth</span>,</p>\n<p>I couldn't find a particular solution to this issue yet. In some cases, It's reported that the error went away on its own (which is very strange).</p>\n<p>Are you noticing this error for all notebooks you tried opening, or a select few?</p>",
        "id": 14295,
        "sender_full_name": "Anderson Banihirwe",
        "timestamp": 1595356256
    },
    {
        "content": "<p>All resolved. Just an issue with full storage on <code>/glade/u/home/</code>. Thanks Anderson!</p>",
        "id": 14378,
        "sender_full_name": "Genevieve Elsworth",
        "timestamp": 1595366230
    },
    {
        "content": "<p>You are very welcome!</p>",
        "id": 14379,
        "sender_full_name": "Anderson Banihirwe",
        "timestamp": 1595366315
    },
    {
        "content": "<p>I'm running into this issue too- is there a way to check how much storage you have on the /glade/u/home? I just ran into this error for the first time today as well and im not sure why.</p>",
        "id": 31613,
        "sender_full_name": "Muntaha Pasha",
        "timestamp": 1621286458
    },
    {
        "content": "<p>you can run <a href=\"https://www2.cisl.ucar.edu/resources/storage-and-file-systems/glade-file-spaces#checkusage\" target=\"_blank\" title=\"https://www2.cisl.ucar.edu/resources/storage-and-file-systems/glade-file-spaces#checkusage\">gladequota</a></p>",
        "id": 31614,
        "sender_full_name": "Matt Long",
        "timestamp": 1621286558
    }
]