<html>
<head><meta charset="utf-8"><title>help with python fetch from old tutorial · CESM-diagnostics · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://127.0.0.1:4000/html/stream/63-CESM-diagnostics/index.html">CESM-diagnostics</a></h2>
<h3>Topic: <a href="http://127.0.0.1:4000/html/stream/63-CESM-diagnostics/topic/help.20with.20python.20fetch.20from.20old.20tutorial.html">help with python fetch from old tutorial</a></h3>

<hr>


<head><link href="http://127.0.0.1:4000/style.css" rel="stylesheet"></head>

<a name="100857"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/63-CESM-diagnostics/topic/help%20with%20python%20fetch%20from%20old%20tutorial/near/100857" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anna-Lena Deppenmeier <a href="http://127.0.0.1:4000/html/stream/63-CESM-diagnostics/topic/help.20with.20python.20fetch.20from.20old.20tutorial.html#100857">(Jun 16 2024 at 21:01)</a>:</h4>
<p>Hi all, I got a question from a user about the data in <a href="https://pop-tools.readthedocs.io/en/latest/examples/CloseHeatBudget_POP2.html#set-up-dataset-to-gather-budget-terms">this example notebook</a>. It looks like fetch doesn't work anymore, does anyone know where these data went? When I try to run the code I get this error<br>
<a href="../../../user_uploads/2/61/Q7S6qePVmHI8XUvVMPzhCjcA/image.png">image.png</a><br>
that ends in <code>error_perm: 550 Failed to open file.</code></p>
<div class="message_inline_image"><a href="../../../user_uploads/2/61/Q7S6qePVmHI8XUvVMPzhCjcA/image.png" title="image.png"><img src="../../../user_uploads/2/61/Q7S6qePVmHI8XUvVMPzhCjcA/image.png"></a></div>



<hr><p>Last updated: May 16 2025 at 17:14 UTC</p>
</html>