<html>
<head><meta charset="utf-8"><title>pooch error in latest pop_tools ¬∑ python-dev ¬∑ Zulip Chat Archive</title></head>
<h2>Stream: <a href="../../..//stream/17-python-dev/index.html">python-dev</a></h2>
<h3>Topic: <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html">pooch error in latest pop_tools</a></h3>

<hr>


<head><link href="../../../style.css" rel="stylesheet"></head>

<a name="6850"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6850" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Keith Lindsay <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6850">(Apr 20 2020 at 18:35)</a>:</h4>
<p>I updated to the latest pop_tools and get the following error when I run <code>import pop_utils</code>:</p>
<div class="codehilite"><pre><span></span>---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
&lt;ipython-input-1-4db41a978446&gt; in &lt;module&gt;
     10 import esmlab
     11 import esmlab_regrid
---&gt; 12 import pop_tools
     13
     14 from gen_remap_weights_1d import gen_remap_weights_1d

/gpfs/fs1/work/klindsay/analysis/pop-tools/pop_tools/__init__.py in &lt;module&gt;
      4 from pkg_resources import DistributionNotFound, get_distribution
      5
----&gt; 6 from .datasets import DATASETS
      7 from .eos import compute_pressure, eos
      8 from .fill import lateral_fill, lateral_fill_np_array

/gpfs/fs1/work/klindsay/analysis/pop-tools/pop_tools/datasets.py in &lt;module&gt;
     14     base_url=&#39;ftp://ftp.cgd.ucar.edu/archive/aletheia-data/cesm-data/ocn/&#39;,
     15 )
---&gt; 16 DATASETS.load_registry(pkg_resources.resource_stream(&#39;pop_tools&#39;, &#39;data_registry.txt&#39;))
     17
     18

/glade/work/klindsay/miniconda3/envs/analysis_dev/lib/python3.7/site-packages/pooch/core.py in load_registry(self, fname)
    342
    343         &quot;&quot;&quot;
--&gt; 344         with open(fname) as fin:
    345             for linenum, line in enumerate(fin):
    346                 elements = line.strip().split()

TypeError: expected str, bytes or os.PathLike object, not _io.BufferedReader
</pre></div>


<p>I don't know what to make of this. Any suggestions on how to avoid this error, or how to further diagnosis the problem?</p>



<a name="6854"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6854" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6854">(Apr 20 2020 at 18:43)</a>:</h4>
<p><span class="user-mention" data-user-id="31">@Keith Lindsay</span>, </p>
<p>What version of <code>pooch</code> are you running?</p>
<p>I just tried importing <code>pop_tools</code> locally and everything seems to be working </p>
<div class="codehilite"><pre><span></span><span class="n">In</span> <span class="p">[</span><span class="mi">1</span><span class="p">]:</span> <span class="kn">import</span> <span class="nn">pop_tools</span>

<span class="n">In</span> <span class="p">[</span><span class="mi">3</span><span class="p">]:</span> <span class="n">exit</span>
</pre></div>
<div class="codehilite"><pre><span></span>pop-tools on ÓÇ† master via üêç v3.7.6 via C analysis via  <span class="m">89</span>%/55% took 38s
‚ùØ conda list pooch                                                                                                                           <span class="o">(</span>analysis<span class="o">)</span> <span class="m">12</span>:41:51
<span class="c1"># packages in environment at /Users/abanihi/opt/miniconda3/envs/analysis:</span>
<span class="c1">#</span>
<span class="c1"># Name                    Version                   Build  Channel</span>
pooch                     <span class="m">1</span>.1.0                      py_0    conda-forge
</pre></div>



<a name="6856"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6856" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Keith Lindsay <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6856">(Apr 20 2020 at 18:52)</a>:</h4>
<p>conda list pooch returns</p>
<div class="codehilite"><pre><span></span># packages in environment at /glade/work/klindsay/miniconda3/envs/analysis_dev:
#
# Name                    Version                   Build  Channel
pooch                     0.2.1                 py37_1000    conda-forge
</pre></div>


<p>I'll try updating it. Fingers crossed that other stuff doesn't break when I update pooch.</p>
<p>I tried to clone my conda environment with the idea of updating pooch in the clone. But the clone failed, so I don't see a safe/reversible way to update pooch.</p>



<a name="6866"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6866" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6866">(Apr 20 2020 at 20:15)</a>:</h4>
<p>Do you have another environment that has <code>pop-tools</code> installed in it?</p>



<a name="6867"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6867" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6867">(Apr 20 2020 at 20:15)</a>:</h4>
<p>Can you try the following and see if it works:</p>
<div class="codehilite"><pre><span></span><span class="n">In</span> <span class="p">[</span><span class="mi">1</span><span class="p">]:</span> <span class="kn">import</span> <span class="nn">pkg_resources</span>

<span class="n">In</span> <span class="p">[</span><span class="mi">2</span><span class="p">]:</span> <span class="n">pkg_resources</span><span class="o">.</span><span class="n">resource_stream</span><span class="p">(</span><span class="s1">&#39;pop_tools&#39;</span><span class="p">,</span> <span class="s1">&#39;data_registry.txt&#39;</span><span class="p">)</span>
<span class="n">Cannot</span> <span class="n">write</span> <span class="n">to</span> <span class="n">data</span> <span class="n">cache</span> <span class="n">folder</span> <span class="s1">&#39;/glade/p/cesmdata/cseg&#39;</span><span class="o">.</span> <span class="n">Will</span> <span class="ow">not</span> <span class="n">be</span> <span class="n">able</span> <span class="n">to</span> <span class="n">download</span> <span class="n">remote</span> <span class="n">data</span> <span class="n">files</span><span class="o">.</span> <span class="n">Use</span> <span class="n">environment</span> <span class="n">variable</span> <span class="s1">&#39;CESMDATAROOT&#39;</span> <span class="n">to</span> <span class="n">specify</span> <span class="n">another</span> <span class="n">directory</span><span class="o">.</span>
<span class="n">Out</span><span class="p">[</span><span class="mi">2</span><span class="p">]:</span> <span class="o">&lt;</span><span class="n">_io</span><span class="o">.</span><span class="n">BufferedReader</span> <span class="n">name</span><span class="o">=</span><span class="s1">&#39;/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/pop_tools/data_registry.txt&#39;</span><span class="o">&gt;</span>
</pre></div>



<a name="6876"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6876" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Keith Lindsay <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6876">(Apr 20 2020 at 20:43)</a>:</h4>
<p>My other environments that have pop-tools are old enough that they don't have the file data_registry.txt.</p>
<p>I'm about to give up on conda updating pooch only. It's been trying for nearly 2 hours to resolve conflicts.</p>
<p>I think I will try to either back up to the older tag of pop-tools that I previously used,<br>
or start a new environment for the notebook that I'm trying to write.</p>



<a name="6884"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6884" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6884">(Apr 20 2020 at 20:53)</a>:</h4>
<p>I tried cloning your environment, but I ran into some issues with packages installed from PyPI:</p>
<div class="codehilite"><pre><span></span>abanihi at casper26 in ~
$ conda create --name analysis_dev_clone --clone /glade/work/klindsay/miniconda3/envs/analysis_dev
Source:      /glade/work/klindsay/miniconda3/envs/analysis_dev
Destination: /glade/work/abanihi/softwares/miniconda3/envs/analysis_dev_clone

PackagesNotFoundError: The following packages are missing from the target environment:
  - <span class="nv">zipp</span><span class="o">==</span><span class="m">0</span>.4.0<span class="o">=</span>pypi_0
  - <span class="nv">seawater</span><span class="o">==</span><span class="m">3</span>.3.4<span class="o">=</span>pypi_0
  - <span class="nv">cfgrib</span><span class="o">==</span><span class="m">0</span>.9.6.2<span class="o">=</span>pypi_0
  - importlib-metadata<span class="o">==</span><span class="m">0</span>.9<span class="o">=</span>pypi_0
  - <span class="nv">typing</span><span class="o">==</span><span class="m">3</span>.6.6<span class="o">=</span>pypi_0
  - pop-tools<span class="o">==</span><span class="m">0</span>.0.post19<span class="o">=</span>dev_0
  - <span class="nv">toml</span><span class="o">==</span><span class="m">0</span>.10.0<span class="o">=</span>pypi_0
  - esmlab-regrid<span class="o">==</span><span class="m">2019</span>.5.2.dev8+g815fd28<span class="o">=</span>dev_0
  - <span class="nv">gitpython</span><span class="o">==</span><span class="m">2</span>.1.11<span class="o">=</span>pypi_0
  - intake-esm<span class="o">==</span><span class="m">2019</span>.4.26.1.post15<span class="o">=</span>pypi_0
  - <span class="nv">watermark</span><span class="o">==</span><span class="m">1</span>.8.1<span class="o">=</span>pypi_0
  - <span class="nv">esmlab</span><span class="o">==</span><span class="m">2019</span>.4.27<span class="o">=</span>pypi_0
  - <span class="nv">virtualenv</span><span class="o">==</span><span class="m">16</span>.5.0<span class="o">=</span>pypi_0
  - <span class="nv">nodeenv</span><span class="o">==</span><span class="m">1</span>.3.3<span class="o">=</span>pypi_0
  - <span class="nv">docrep</span><span class="o">==</span><span class="m">0</span>.2.5<span class="o">=</span>pypi_0
  - <span class="nv">cfgv</span><span class="o">==</span><span class="m">1</span>.6.0<span class="o">=</span>pypi_0
  - <span class="nv">gitdb2</span><span class="o">==</span><span class="m">2</span>.0.5<span class="o">=</span>pypi_0
  - ncar-jobqueue<span class="o">==</span><span class="m">2019</span>.3.8<span class="o">=</span>pypi_0
  - <span class="nv">nbdime</span><span class="o">==</span><span class="m">1</span>.0.5<span class="o">=</span>pypi_0
  - <span class="nv">colorama</span><span class="o">==</span><span class="m">0</span>.4.1<span class="o">=</span>pypi_0
  - dask-jobqueue<span class="o">==</span><span class="m">0</span>.4.1+30.g779bea3<span class="o">=</span>pypi_0
  - <span class="nv">smmap2</span><span class="o">==</span><span class="m">2</span>.0.5<span class="o">=</span>pypi_0
  - pre-commit<span class="o">==</span><span class="m">1</span>.15.2<span class="o">=</span>pypi_0
  - <span class="nv">identify</span><span class="o">==</span><span class="m">1</span>.4.2<span class="o">=</span>pypi_0
  - msgpack-python<span class="o">==</span><span class="m">0</span>.5.6<span class="o">=</span>pypi_0
  - <span class="nv">xcollection</span><span class="o">==</span><span class="m">0</span>+untagged.60.g1905fea<span class="o">=</span>pypi_0
  - aspy-yaml<span class="o">==</span><span class="m">1</span>.2.0<span class="o">=</span>pypi_0
</pre></div>



<a name="6885"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6885" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Keith Lindsay <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6885">(Apr 20 2020 at 20:59)</a>:</h4>
<p>I got the same errors when I attempted to clone the environment myself.<br>
It's unclear to me where the packages are missing from.</p>



<a name="6886"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6886" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6886">(Apr 20 2020 at 21:03)</a>:</h4>
<p>Try the following</p>



<a name="6887"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6887" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6887">(Apr 20 2020 at 21:03)</a>:</h4>
<div class="codehilite"><pre><span></span>conda list --explicit &gt; spec-file.txt
</pre></div>



<a name="6888"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6888" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6888">(Apr 20 2020 at 21:03)</a>:</h4>
<div class="codehilite"><pre><span></span>conda install --name myenv --file spec-file.txt
</pre></div>



<a name="6890"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/17-python-dev/topic/pooch%20error%20in%20latest%20pop_tools/near/6890" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Deepak Cherian <a href="../../..//stream/17-python-dev/topic/pooch.20error.20in.20latest.20pop_tools.html#6890">(Apr 20 2020 at 21:30)</a>:</h4>
<p>anecdotally, if your environment is too old, updating single packages makes everything fall flat. There are too many possible solutions (I think). Usually <code>conda update --all</code> will complete in a reasonable amount of time.</p>



<hr><p>Last updated: May 16 2025 at 17:14 UTC</p>
</html>