[
    {
        "content": "<p>Hello. After installing the Python module pycwt in my conda environment, I can no longer import xarray. It seems like xarray was updated, which probably caused a conflict with numba. I don't have permission to update numba. Does anyone have any idea how I should proceed? I have attached a picture of the error. Thanks in advance.<br>\n<a href=\"/user_uploads/2/c5/RdqD9gjXr9yJS2-n0oKaNJRA/error.png\">error.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/c5/RdqD9gjXr9yJS2-n0oKaNJRA/error.png\" title=\"error.png\"><img src=\"/user_uploads/2/c5/RdqD9gjXr9yJS2-n0oKaNJRA/error.png\"></a></div>",
        "id": 104524,
        "sender_full_name": "Maurício Rebouças Rocha",
        "timestamp": 1728652977
    },
    {
        "content": "<p>How did you install <code>pycwt</code>? I'm guessing you used <code>pip</code>, and maybe that caused problems by installing updated versions of some dependencies? It looks like <code>PyCWT</code> <a href=\"https://pycwt.readthedocs.io/en/latest/user-guide/installation/#requirements\">only depends on</a> <code>numpy</code>, <code>scipy</code>, <code>matplotlib</code>, and <code>tqdm</code> so my hypothesis is that <code>pip</code> installed a newer version of one (or more) of those packages that is conflicting with what <code>conda</code> can load, though maybe it updated <code>numba</code> as well? Here's what I see from the vanilla <code>npl-2022b</code> environment, where I have verified I can import <code>xarray</code>:</p>\n<div class=\"codehilite\" data-code-language=\"Bash\"><pre><span></span><code>$<span class=\"w\"> </span>conda<span class=\"w\"> </span>activate<span class=\"w\"> </span>npl-2022b\n<span class=\"o\">(</span>npl-2022b<span class=\"o\">)</span><span class=\"w\"> </span>$<span class=\"w\"> </span><span class=\"k\">for</span><span class=\"w\"> </span>package<span class=\"w\"> </span><span class=\"k\">in</span><span class=\"w\"> </span>xarray<span class=\"w\"> </span>numpy<span class=\"w\"> </span>scipy<span class=\"w\"> </span>matplotlib<span class=\"w\"> </span>tqdm<span class=\"w\"> </span>numba<span class=\"p\">;</span><span class=\"w\"> </span><span class=\"k\">do</span><span class=\"w\"> </span>conda<span class=\"w\"> </span>list<span class=\"w\"> </span><span class=\"p\">|</span><span class=\"w\"> </span>grep<span class=\"w\"> </span>^<span class=\"si\">${</span><span class=\"nv\">package</span><span class=\"si\">}</span><span class=\"p\">;</span><span class=\"w\"> </span>pip<span class=\"w\"> </span>list<span class=\"w\"> </span><span class=\"p\">|</span><span class=\"w\"> </span>grep<span class=\"w\"> </span>^<span class=\"si\">${</span><span class=\"nv\">package</span><span class=\"si\">}</span><span class=\"p\">;</span><span class=\"w\"> </span><span class=\"k\">done</span>\nxarray<span class=\"w\">                    </span><span class=\"m\">2022</span>.6.0<span class=\"w\">           </span>pyhd8ed1ab_1<span class=\"w\">    </span>conda-forge\nxarray<span class=\"w\">                        </span><span class=\"m\">2022</span>.6.0\nnumpy<span class=\"w\">                     </span><span class=\"m\">1</span>.23.1<span class=\"w\">           </span>py38h3a7f9d9_0<span class=\"w\">    </span>conda-forge\nnumpy<span class=\"w\">                         </span><span class=\"m\">1</span>.23.1\nscipy<span class=\"w\">                     </span><span class=\"m\">1</span>.9.0<span class=\"w\">            </span>py38hea3f02b_0<span class=\"w\">    </span>conda-forge\nscipy<span class=\"w\">                         </span><span class=\"m\">1</span>.9.0\nmatplotlib<span class=\"w\">                </span><span class=\"m\">3</span>.5.2<span class=\"w\">            </span>py38h578d9bd_1<span class=\"w\">    </span>conda-forge\nmatplotlib-base<span class=\"w\">           </span><span class=\"m\">3</span>.5.2<span class=\"w\">            </span>py38h826bfd8_1<span class=\"w\">    </span>conda-forge\nmatplotlib-inline<span class=\"w\">         </span><span class=\"m\">0</span>.1.3<span class=\"w\">              </span>pyhd8ed1ab_0<span class=\"w\">    </span>conda-forge\nmatplotlib<span class=\"w\">                    </span><span class=\"m\">3</span>.5.2\nmatplotlib-inline<span class=\"w\">             </span><span class=\"m\">0</span>.1.3\ntqdm<span class=\"w\">                      </span><span class=\"m\">4</span>.64.0<span class=\"w\">             </span>pyhd8ed1ab_0<span class=\"w\">    </span>conda-forge\ntqdm<span class=\"w\">                          </span><span class=\"m\">4</span>.64.0\nnumba<span class=\"w\">                     </span><span class=\"m\">0</span>.53.1<span class=\"w\">           </span>py38h8b71fd7_1<span class=\"w\">    </span>conda-forge\nnumba<span class=\"w\">                         </span><span class=\"m\">0</span>.53.1\n</code></pre></div>\n<p>What happens when you run that bash command? Do you see differences in the version numbers, either compared to mine or where the first line [conda version] differs from the second line [pip version]?</p>\n<p>As far as solutions go, I think you need to uninstall pycwt and whatever dependencies it install that are causing problems with <code>xarray</code>, verify that <code>xarray</code> can be loaded again, and then maybe installing an older version of <code>pycwt</code> (e.g. <a href=\"https://github.com/regeirk/pycwt/commit/d53dbe43deaf0c9d3aa54ae34f198386ef62e903\">https://github.com/regeirk/pycwt/commit/d53dbe43deaf0c9d3aa54ae34f198386ef62e903</a> is from spring 2023) will play nicely with the conda-installed versions of the above packages?</p>",
        "id": 104525,
        "sender_full_name": "Michael Levy",
        "timestamp": 1728656419
    },
    {
        "content": "<p>Hi Mike, thanks for replying. Yes, I had installed pycwt using pip, but I've uninstalled it now. After the bash command, I got the following: <br>\n<a href=\"/user_uploads/2/d8/HoDmDIlixrmrmojFM6G7FThk/Screenshot1.png\">Screenshot1.png</a>  The error persists even after uninstalling pycwt.</p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/d8/HoDmDIlixrmrmojFM6G7FThk/Screenshot1.png\" title=\"Screenshot1.png\"><img src=\"/user_uploads/2/d8/HoDmDIlixrmrmojFM6G7FThk/Screenshot1.png\"></a></div>",
        "id": 104526,
        "sender_full_name": "Maurício Rebouças Rocha",
        "timestamp": 1728658206
    },
    {
        "content": "<p>It looks like all four packages got updated -- can you run <code>pip uninstall numpy scipy matplotlib tqdm</code>? I think that's the right syntax...</p>",
        "id": 104527,
        "sender_full_name": "Michael Levy",
        "timestamp": 1728658636
    },
    {
        "content": "<p>then check to see if <code>xarray</code> can be imported again</p>",
        "id": 104528,
        "sender_full_name": "Michael Levy",
        "timestamp": 1728658651
    },
    {
        "content": "<p>Also, when you try to reinstall pywct, you might be able to use</p>\n<div class=\"codehilite\"><pre><span></span><code>$ pip install --use-feature=2020-resolver -e .\n</code></pre></div>\n<p>To force it to either use the installed versions from conda or give you an error about why it needs to update one (or more) of them, though my understanding is that the default should not have tried to update anything unless the dependency list demanded it</p>",
        "id": 104529,
        "sender_full_name": "Michael Levy",
        "timestamp": 1728658944
    },
    {
        "content": "<p>Got it, it worked. Thank you. I'll try installing pycwt again following your suggestion.</p>",
        "id": 104530,
        "sender_full_name": "Maurício Rebouças Rocha",
        "timestamp": 1728659307
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"266\">Maurício Rebouças Rocha</span> has marked this topic as resolved.</p>",
        "id": 104531,
        "sender_full_name": "Notification Bot",
        "timestamp": 1728659710
    }
]